name: Deploy

# Trigger the workflow on push and 
# pull request events on the master branch
on:
  push:
    branches: [ master ]
      
# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: 
            cd /var/www/ultronarmy_eu/ultron01/projekty/TeamRegister && ./.scripts/deploy.sh